#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : akonadi-calendar-tools
Version  : 18.12.3
Release  : 4
URL      : https://download.kde.org/stable/applications/18.12.3/src/akonadi-calendar-tools-18.12.3.tar.xz
Source0  : https://download.kde.org/stable/applications/18.12.3/src/akonadi-calendar-tools-18.12.3.tar.xz
Source99 : https://download.kde.org/stable/applications/18.12.3/src/akonadi-calendar-tools-18.12.3.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.2 GPL-2.0 LGPL-2.1
Requires: akonadi-calendar-tools-bin = %{version}-%{release}
Requires: akonadi-calendar-tools-data = %{version}-%{release}
Requires: akonadi-calendar-tools-license = %{version}-%{release}
Requires: akonadi-calendar-tools-locales = %{version}-%{release}
BuildRequires : akonadi-calendar-dev
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : calendarsupport-dev
BuildRequires : kcalcore-dev
BuildRequires : kcalutils-dev
BuildRequires : kcontacts-dev
BuildRequires : kidentitymanagement-dev
BuildRequires : kmime-dev
BuildRequires : kpimtextedit-dev
BuildRequires : libkdepim-dev
BuildRequires : qtbase-dev mesa-dev

%description
Here are some nice example scripts how to use konsolekalendar.
* tcm2kcal.pl
Parses TCM (Turner Classic Movies) schedule from the web site to ICS
You need lynx and the Date::Calc to use this script
(you can install Date::Calc using 'perl -MCPAN -e 'install Date::Calc')

%package bin
Summary: bin components for the akonadi-calendar-tools package.
Group: Binaries
Requires: akonadi-calendar-tools-data = %{version}-%{release}
Requires: akonadi-calendar-tools-license = %{version}-%{release}

%description bin
bin components for the akonadi-calendar-tools package.


%package data
Summary: data components for the akonadi-calendar-tools package.
Group: Data

%description data
data components for the akonadi-calendar-tools package.


%package doc
Summary: doc components for the akonadi-calendar-tools package.
Group: Documentation

%description doc
doc components for the akonadi-calendar-tools package.


%package license
Summary: license components for the akonadi-calendar-tools package.
Group: Default

%description license
license components for the akonadi-calendar-tools package.


%package locales
Summary: locales components for the akonadi-calendar-tools package.
Group: Default

%description locales
locales components for the akonadi-calendar-tools package.


%prep
%setup -q -n akonadi-calendar-tools-18.12.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552022499
mkdir -p clr-build
pushd clr-build
export LDFLAGS="${LDFLAGS} -fno-lto"
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1552022499
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/akonadi-calendar-tools
cp COPYING %{buildroot}/usr/share/package-licenses/akonadi-calendar-tools/COPYING
cp COPYING.DOC %{buildroot}/usr/share/package-licenses/akonadi-calendar-tools/COPYING.DOC
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/akonadi-calendar-tools/COPYING.LIB
cp calendarjanitor/COPYING %{buildroot}/usr/share/package-licenses/akonadi-calendar-tools/calendarjanitor_COPYING
cp konsolekalendar/COPYING %{buildroot}/usr/share/package-licenses/akonadi-calendar-tools/konsolekalendar_COPYING
pushd clr-build
%make_install
popd
%find_lang calendarjanitor
%find_lang konsolekalendar

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/calendarjanitor
/usr/bin/konsolekalendar

%files data
%defattr(-,root,root,-)
/usr/share/applications/konsolekalendar.desktop
/usr/share/icons/hicolor/128x128/apps/konsolekalendar.png
/usr/share/icons/hicolor/16x16/apps/konsolekalendar.png
/usr/share/icons/hicolor/22x22/apps/konsolekalendar.png
/usr/share/icons/hicolor/32x32/apps/konsolekalendar.png
/usr/share/icons/hicolor/48x48/apps/konsolekalendar.png
/usr/share/xdg/console.categories
/usr/share/xdg/console.renamecategories

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/ca/konsolekalendar/index.docbook
/usr/share/doc/HTML/de/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/de/konsolekalendar/index.docbook
/usr/share/doc/HTML/en/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/en/konsolekalendar/index.docbook
/usr/share/doc/HTML/es/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/es/konsolekalendar/index.docbook
/usr/share/doc/HTML/et/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/et/konsolekalendar/index.docbook
/usr/share/doc/HTML/it/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/it/konsolekalendar/index.docbook
/usr/share/doc/HTML/nl/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/nl/konsolekalendar/index.docbook
/usr/share/doc/HTML/pt/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/pt/konsolekalendar/index.docbook
/usr/share/doc/HTML/pt_BR/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/pt_BR/konsolekalendar/index.docbook
/usr/share/doc/HTML/ru/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/ru/konsolekalendar/index.docbook
/usr/share/doc/HTML/sv/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/sv/konsolekalendar/index.docbook
/usr/share/doc/HTML/uk/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/uk/konsolekalendar/index.docbook

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/akonadi-calendar-tools/COPYING
/usr/share/package-licenses/akonadi-calendar-tools/COPYING.DOC
/usr/share/package-licenses/akonadi-calendar-tools/COPYING.LIB
/usr/share/package-licenses/akonadi-calendar-tools/calendarjanitor_COPYING
/usr/share/package-licenses/akonadi-calendar-tools/konsolekalendar_COPYING

%files locales -f calendarjanitor.lang -f konsolekalendar.lang
%defattr(-,root,root,-)

