#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : akonadi-calendar-tools
Version  : 20.12.0
Release  : 27
URL      : https://download.kde.org/stable/release-service/20.12.0/src/akonadi-calendar-tools-20.12.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/20.12.0/src/akonadi-calendar-tools-20.12.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/20.12.0/src/akonadi-calendar-tools-20.12.0.tar.xz.sig
Summary  : CLI tools to manage akonadi calendars
Group    : Development/Tools
License  : GFDL-1.2 GPL-2.0
Requires: akonadi-calendar-tools-bin = %{version}-%{release}
Requires: akonadi-calendar-tools-data = %{version}-%{release}
Requires: akonadi-calendar-tools-license = %{version}-%{release}
Requires: akonadi-calendar-tools-locales = %{version}-%{release}
BuildRequires : akonadi-calendar-dev
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : calendarsupport-dev
BuildRequires : extra-cmake-modules-data
BuildRequires : kcalendarcore-dev
BuildRequires : kcalutils-dev
BuildRequires : kcontacts-dev
BuildRequires : kdoctools-dev
BuildRequires : ki18n-dev
BuildRequires : kidentitymanagement-dev
BuildRequires : kmime-dev
BuildRequires : kpimtextedit-dev
BuildRequires : libkdepim-dev
BuildRequires : qtbase-dev mesa-dev

%description
Here are some nice example scripts how to use konsolekalendar.
* tcm2kcal.pl
Parses TCM (Turner Classic Movies) schedule from the web site to ICS
You need lynx and the Date::Calc to use this script
(you can install Date::Calc using 'perl -MCPAN -e 'install Date::Calc')

%package bin
Summary: bin components for the akonadi-calendar-tools package.
Group: Binaries
Requires: akonadi-calendar-tools-data = %{version}-%{release}
Requires: akonadi-calendar-tools-license = %{version}-%{release}

%description bin
bin components for the akonadi-calendar-tools package.


%package data
Summary: data components for the akonadi-calendar-tools package.
Group: Data

%description data
data components for the akonadi-calendar-tools package.


%package doc
Summary: doc components for the akonadi-calendar-tools package.
Group: Documentation

%description doc
doc components for the akonadi-calendar-tools package.


%package license
Summary: license components for the akonadi-calendar-tools package.
Group: Default

%description license
license components for the akonadi-calendar-tools package.


%package locales
Summary: locales components for the akonadi-calendar-tools package.
Group: Default

%description locales
locales components for the akonadi-calendar-tools package.


%prep
%setup -q -n akonadi-calendar-tools-20.12.0
cd %{_builddir}/akonadi-calendar-tools-20.12.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1607918692
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1607918692
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/akonadi-calendar-tools
cp %{_builddir}/akonadi-calendar-tools-20.12.0/LICENSES/GFDL-1.2-or-later.txt %{buildroot}/usr/share/package-licenses/akonadi-calendar-tools/7697008f58568e61e7598e796eafc2a997503fde
cp %{_builddir}/akonadi-calendar-tools-20.12.0/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/akonadi-calendar-tools/e712eadfab0d2357c0f50f599ef35ee0d87534cb
pushd clr-build
%make_install
popd
%find_lang calendarjanitor
%find_lang konsolekalendar

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/calendarjanitor
/usr/bin/konsolekalendar

%files data
%defattr(-,root,root,-)
/usr/share/applications/konsolekalendar.desktop
/usr/share/icons/hicolor/128x128/apps/konsolekalendar.png
/usr/share/icons/hicolor/16x16/apps/konsolekalendar.png
/usr/share/icons/hicolor/22x22/apps/konsolekalendar.png
/usr/share/icons/hicolor/32x32/apps/konsolekalendar.png
/usr/share/icons/hicolor/48x48/apps/konsolekalendar.png
/usr/share/qlogging-categories5/console.categories
/usr/share/qlogging-categories5/console.renamecategories

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/ca/konsolekalendar/index.docbook
/usr/share/doc/HTML/de/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/de/konsolekalendar/index.docbook
/usr/share/doc/HTML/en/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/en/konsolekalendar/index.docbook
/usr/share/doc/HTML/es/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/es/konsolekalendar/index.docbook
/usr/share/doc/HTML/et/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/et/konsolekalendar/index.docbook
/usr/share/doc/HTML/it/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/it/konsolekalendar/index.docbook
/usr/share/doc/HTML/nl/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/nl/konsolekalendar/index.docbook
/usr/share/doc/HTML/pt/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/pt/konsolekalendar/index.docbook
/usr/share/doc/HTML/pt_BR/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/pt_BR/konsolekalendar/index.docbook
/usr/share/doc/HTML/ru/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/ru/konsolekalendar/index.docbook
/usr/share/doc/HTML/sv/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/sv/konsolekalendar/index.docbook
/usr/share/doc/HTML/uk/konsolekalendar/index.cache.bz2
/usr/share/doc/HTML/uk/konsolekalendar/index.docbook

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/akonadi-calendar-tools/7697008f58568e61e7598e796eafc2a997503fde
/usr/share/package-licenses/akonadi-calendar-tools/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f calendarjanitor.lang -f konsolekalendar.lang
%defattr(-,root,root,-)

